name: Update Repository

on:
  repository_dispatch:
    types: [package-updated]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  update-repo:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
      - name: Install git
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          cd $GITHUB_WORKSPACE
          git init
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add origin https://github.com/$GITHUB_REPOSITORY.git

      - name: Install dependencies
        run: |
          pacman -S --noconfirm repo-add

      - name: Download package
        if: github.event_name == 'repository_dispatch'
        run: |
          mkdir -p x86_64
          cd x86_64
          wget https://github.com/teamnebulaos/${{ github.event.client_payload.package }}/releases/download/${{ github.event.client_payload.version }}/*.pkg.tar.zst

      - name: Update repository
        run: |
          cd x86_64
          repo-add -n -R nebula.db.tar.gz *.pkg.tar.zst
          
      - name: Push changes
        run: |
          git add .
          git commit -m "Update repository"
          git push origin main

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: repo
          name: Repository Update
          draft: false
          prerelease: false
          files: |
            x86_64/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
